# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18_bpEP2JHgpDZhGcFafCl5EWP_GQtja9
"""

# pip install python-chess

import chess.pgn, io, pandas as pd

pgn_text = """
[Event "Live Chess"]
[Site "Chess.com"]
[Date "2023.09.10"]
[Round "?"]
[White "suniax3"]
[Black "navinmundhra"]
[Result "0-1"]
[ECO "C40"]
[WhiteElo "729"]
[BlackElo "724"]
[TimeControl "600"]
[EndTime "10:07:11 PDT"]
[Termination "navinmundhra won by resignation"]

1. e4 e5 2. Nf3 Qe7 3. d4 f6 4. Be3 Nc6 5. d5 Nb4 6. Bd2 c6 7. c3 Na6 8. dxc6
dxc6 9. Bc4 Bg4 10. h3 Bxf3 11. Qxf3 Nc5 12. O-O O-O-O 13. Be3 Qd6 14. Rd1 Qe7
15. Nd2 Qc7 16. Qf5+ Kb8 17. f4 Ne7 18. Qg4 Ng6 19. Nf3 Nxe4 20. Bd3 f5 21. Bf2
0-1
"""

pgn = chess.pgn.read_game(io.StringIO(pgn_text))

move_number = 1
table_format = []

board = pgn.board()

for move in pgn.mainline_moves():
    move_san = board.san(move)

    move_str = str(move)
    piece_name = board.piece_at(move.from_square).symbol()
    cell_from = chess.square_name(move.from_square)
    cell_to = chess.square_name(move.to_square)

    table_format.append((move_number, piece_name, cell_from, cell_to, move_san))

    board.push(move)

    move_number += 1

columns = ["Move Number", "Piece Name", "Cell From", "Cell To", "Move SAN"]
df = pd.DataFrame(table_format, columns=columns)

print(df)